from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Iterator
from dataclasses import dataclass, field
from typing import Any

import pandas as pd


@dataclass
class IngestionJob:
    """Unit of work generated by a partitioner."""

    params: dict[str, Any]
    meta: dict[str, Any] = field(default_factory=dict)


class BasePartitioner(ABC):
    """Split a scope into smaller ingestion jobs."""

    @abstractmethod
    def generate_jobs(
        self, start_date: str | None = None, end_date: str | None = None, **kwargs
    ) -> Iterator[IngestionJob]:
        pass


class BaseExtractor(ABC):
    """Execute a single job and return raw data."""

    @abstractmethod
    def extract(self, job: IngestionJob) -> pd.DataFrame | None:
        pass


class BaseCompactor(ABC):
    """Persist extracted data into final storage."""

    @abstractmethod
    def compact(
        self, results: list[Any], target: str, partition_date: str, **kwargs
    ) -> dict[str, Any]:
        pass
